### ISSUE TITLE
Missing logout functionality

### ISSUE THREAD

**Issue by WilhelmOks** [OmerFlame/SwiftRant#2]
There seems to be no way to log out after a log in.
I've looked up how you do it in the AltRant app and you remove the token from the keychain directly.
Modifying the code a bit, this is what works for me now:

        let keychainWrapper = KeychainWrapper(
            serviceName: "SwiftRant",
            accessGroup: "SwiftRantAccessGroup"
        )
        
        let query: [String:Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecReturnAttributes as String: true,
            kSecReturnData as String: true,
        ]
        
        keychainWrapper.removeAllKeys()
        SecItemDelete(query as CFDictionary)

I suggest to wrap it into a logout function in SwiftRant.

**Comment by OmerFlame** [comment]
Thank you! I will add it later today, including the missing documentation in the last issue.

**Comment by OmerFlame** [comment]
Sadly, my computer has issues with the Xcode toolchains and stuff, can you please make a pull request? I want to approve this change, it's pretty important.

**Comment by WilhelmOks** [comment]
I created the PR.
Please make a new version after merging, so that it gets updated via SPM :)

**Comment by OmerFlame** [comment]
No problem.

**Comment by OmerFlame** [comment]
I've released a new version!
