### ISSUE TITLE
Collaboration Invitation for @WilhelmOks

### ISSUE THREAD

**Issue by OmerFlame** [OmerFlame/SwiftRant#6]
**This is directed towards @WilhelmOks**

I hope this finds you well!

Since you've been contributing so much to this repo, I figured that adding you to the list of collaborators and giving you direct access to the repo would be smart, since maintaining this project alone is a bit difficult and taking in outside opinion and quality control has been basically impossible... since there is no one using the library at the moment except for me and you.

My current plan is the following:

When I am unable to improve on existing code (I am also starting professional college in 2 days), you will be able to improve on it yourself, as long as you are not maliciously modifying and/or destroying code. I am willing to put my trust in you, since you are showing active dependence and interest in this project. If you will join me, then all changes (including mine) will be based on pull requests and will be reviewed by each other together instead of merging/pushing to main on a whim going forward. When I will **actually** start kicking into gear with this library again, I will work on adding core functionality (more API interface methods and tests), and you will be able to help me review the quality of my additions, improvements and implementations.

Please tell me if you are interested in maintaining this project with me in a professional manner, I will be happy to work with you!

**This project is far from dead!**

Edit: fixed typo

**Comment by WilhelmOks** [comment]
Hey, thank you for this offer. 
I'm in vacation at the moment. That's why I had time to do this stuff. When I'll be back at work, I won't have this time anymore.
So, while I'd be glad to contribute, I won't be able to review every PR in time.

**Comment by OmerFlame** [comment]
I appreciate your honesty! I really thank you for helping with the library in your free time, I am happy that I am building libraries that people are willing to use. I will continue adding more features to this library in the very near future, as it seems at the moment.
